### ISSUE TITLE
liquid.builtin.tags.for_tag.BreakNode and ContinueNode do not implement children(), causing analyze() to raise

### ISSUE THREAD

**Issue by brian-vanderford** [jg-rp/liquid#89]
```
>>> from liquid import Environment
>>> Environment().from_string("{% for foo in bar %} {% break %} {% endfor %}").analyze()         
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brian/src/cloudtruth/conserv/ctcaas/.tox/run/lib/python3.9/site-packages/liquid/template.py", line 284, in analyze
    refs = _TemplateVariableCounter(
  File "/home/brian/src/cloudtruth/conserv/ctcaas/.tox/run/lib/python3.9/site-packages/liquid/template.py", line 622, in analyze
    self._raise_for_failures()
  File "/home/brian/src/cloudtruth/conserv/ctcaas/.tox/run/lib/python3.9/site-packages/liquid/template.py", line 907, in _raise_for_failures
    raise TemplateTraversalError(f"failed visit: {msg}")
liquid.exceptions.TemplateTraversalError: failed visit: BreakNode does not implement a 'children' method
>>> Environment().from_string("{% for foo in bar %} {% continue %} {% endfor %}").analyze()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brian/src/cloudtruth/conserv/ctcaas/.tox/run/lib/python3.9/site-packages/liquid/template.py", line 284, in analyze
    refs = _TemplateVariableCounter(
  File "/home/brian/src/cloudtruth/conserv/ctcaas/.tox/run/lib/python3.9/site-packages/liquid/template.py", line 622, in analyze
    self._raise_for_failures()
  File "/home/brian/src/cloudtruth/conserv/ctcaas/.tox/run/lib/python3.9/site-packages/liquid/template.py", line 907, in _raise_for_failures
    raise TemplateTraversalError(f"failed visit: {msg}")
liquid.exceptions.TemplateTraversalError: failed visit: ContinueNode does not implement a 'children' method
```

It looks like they want children methods that return an empty list?

**Comment by jg-rp** [comment]
Thanks @brian-vanderford. Not sure how I managed to miss that.

Fixed in version 1.6.1, now released.
